"""create_notepad_model

Revision ID: 202269d7f958
Revises: a76b59048add
Create Date: 2024-09-25 14:06:52.041270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202269d7f958'
down_revision = 'a76b59048add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notepad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notepad')
    # ### end Alembic commands ###
